### ISSUE TITLE
[FEATURE] Custom icon for keyboard shortcuts?

### ISSUE THREAD

**Issue by heymartinadams** [harshhhdev/kmenu#105]
Many users don’t know what “meta” means. Any chance we can show keyboard shortcut icons instead?

![CleanShot 2024-01-22 at 15 21 14@2x](https://github.com/harshhhdev/kmenu/assets/11673745/a91ef808-cd26-4dcd-ae9e-e01887053061)

**Comment by harshhhdev** [comment]
@heymartinadams I believe this is already a feature. You just have to put an SVG in the slot.

Here is an example from another company that uses kmenu:

<img width="630" alt="image" src="https://github.com/harshhhdev/kmenu/assets/69592270/920be1b7-5545-492e-a38f-cf0c8c3fbfed">

**Comment by heymartinadams** [comment]
Awesome, thanks!
