### ISSUE TITLE
[BUG] Type definitions prevent children for MenuProvider

### ISSUE THREAD

**Issue by hrishioa** [harshhhdev/kmenu#13]
Trying out kmenu for a small personal project, awesome work!

**Describe the bug**
Trying to run the example project, as well as import into my own, gives the following error:
```
Type '{ children: Element; }' has no properties in common with type 'IntrinsicAttributes & Pick<MenuContext, "config" | "dimensions">'.  TS2559

     8 | const App = () => {
     9 |   return (
  > 10 |     <MenuProvider>
       |      ^
    11 |       <main className={styles.main}>
    12 |         <h1 className={styles.title}>Hello, World!</h1>
    13 |         <p className={styles.description}>
```
Simple fix:
Update type definition for `MenuProvider` in `kmenu/dist/types.d.ts` to:
```typescript
export declare type MenuProviderProps = Pick<MenuContext, 'config' | 'dimensions'> & {children: JSX.Element};
```

**To Reproduce**
1. Clone this repo.
2. `cd example`
3. `yarn install && yarn start`
4. Node version: 14.18.1, Typescript version 3.9.10

## Out-of-context query

Is there a better way to style the menu other than using the random class names? Appreciate any help!

**Comment by harshhhdev** [comment]
Hey @hrishioa, thanks for using kmenu. I'm glad you like it. 

I don't have this issue, but I will look into it. Which version of kmenu are you using? 

Also, for the class names -- thanks for pointing that out. I will come up with something better in the next release.

**Comment by hrishioa** [comment]
Thanks! I'm on v1.0.0beta.

**Comment by harshhhdev** [comment]
@hrishioa try updating to the @1.0.0-beta-dev. That should fix it.

**Comment by harshhhdev** [comment]
As a side note, I've also removed CSS modules and created more accessible module names for you to style them yourself.

**Comment by hrishioa** [comment]
Sounds good - I'll try upgrading.

**Comment by harshhhdev** [comment]
I've also just released `v1-beta-git`. You can read the release notes [here](https://github.com/harshhhdev/kmenu/releases/tag/v1-beta-git).
