### ISSUE TITLE
[FEATURE] Add ability to have different placeholders on nested menus

### ISSUE THREAD

**Issue by julesbravo** [harshhhdev/kmenu#35]
**Is your feature request related to a problem? Please describe.**
It would be a better UX for my users to be able to switch the placeholder text when clicking into a nested menu.

**Describe the solution you'd like**
Add an option to override the placeholder on a `CommandMenu`.

**Describe alternatives you've considered**
I've considered trying to write JS to detect when someone goes into a nested menu and update the placeholder, but that seemed dirty.

**Additional context**
None

**Comment by harshhhdev** [comment]
Hey @julesbravo, that seems like a great addition. 
The alternative sounds very frustrating and confusing indeed, I'll be looking at implementing this tomorrow or this weekend.

**Comment by harshhhdev** [comment]
You can now use placeholders in `kmenu@v1.2.1-dev`. 
Update using `npm i kmenu@latest`.
