### ISSUE TITLE
[BUG] Bar blocks elements behind it even when it's closed

### ISSUE THREAD

**Issue by harshhhdev** [harshhhdev/kmenu#6]
**Describe the bug**
In some SPECIAL CASES, when I click cmdk to toggle the bar it doesn't close properly.

**To Reproduce**
I'm not sure what exactly is causing this bug, because the command menu on [kmenu.hxrsh.in](https://kmenu.hxrsh.in/) and the one in the `example` directory both work fine. However on the [StackBlitz](https://stackblitz.com/edit/react-ts-fotwq9) example that I've created doesn't close the menu properly. While it does make the opacity zero, it doesn't close the menu.

I've also tried console logging values but no luck there either.

**Expected behavior**
I'd expect the opacity to become zero as well as having the bar out of sight.

**Screenshots**

![image](https://user-images.githubusercontent.com/69592270/181814085-4f29aa76-7778-48c7-8be6-2dc91e2feeef.png)

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser: Chromium/Brave
 - Version: 0.2.25-dev

**Additional context**
None

**Comment by harshhhdev** [comment]
I am having trouble reproducing this. If this has happened with anybody, please do let me know.

**Comment by hrishioa** [comment]
This is happening with me as well. Trying to debug, will post anything I find.

I'm on
* OS: MacOS 12.4
* Browser: Chrome 104.0
* Node: 14.18.1

**Comment by harshhhdev** [comment]
Hey @hrishioa, in the latest update of kmenu this will be fixed.
I'm facing this bug too, but it happens only in development. It goes away in production,

**Comment by harshhhdev** [comment]
It's been fixed in the recent `v1.0.0-beta-git` release. I'm unable to reproduce it, so I'll close it unless you still encounter it.
